# 数据源配置
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: ${DATASOURCE_URL:jdbc:mysql://yueyue0313.dynv6.net:3306/test_lesson?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true&allowMultiQueries=true&allowPublicKeyRetrieval=true}
    username: ${DATASOURCE_USERNAME:test_lesson}
    password: ${DATASOURCE_PWD:20766666}

mybatis:
  mapper-locations: classpath:mappers/*.xml
